### ISSUE TITLE
Wireless Dimmer states

### ISSUE THREAD

**Issue by tundratier** [justme-1968/tradfri-fhem#1]
First of: Controlling the IKEA LED Lamps with the library works flawlessly!

I know that the forum entry states that "the controls can only read battery state". Is this a technical limitation or is it "just" not implemented, yet?

Because I would like to read the saturation state of the wireless dimmer.
(https://www.ikea.com/de/de/p/tradfri-kabelloser-dimmer-weiss-00347831/)

If I can be of any help regarding this issue please let me know how.

**Comment by justme-1968** [comment]
it looks like the ikea gateway does not transmit other values besides battery level for any of the sensors (remotes, motion sensor). it looks like there is nothing that can be done. at least at the moment.

using the deCONZ bridge instead of the ikea gateway would give you these values.
